# Generated by Django 6.0.1 on 2026-03-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(default='maintain', max_length=20),
        ),
    ]
