# Generated by Django 6.0.1 on 2026-03-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
