# Generated by Django 6.0.1 on 2026-03-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_allergies_userprofile_health_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
