# Generated by Django 6.0.1 on 2026-03-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_emailotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='user',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
