# Generated by Django 6.0.1 on 2026-03-06 22:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dietplan_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
